# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-05-25 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique_for_date='posted', verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('content', models.TextField()),
                ('image', imagekit.models.fields.ProcessedImageField(help_text='\u0411\u0443\u0434\u0435\u0442 \u043b\u0443\u0447\u0448\u0435 \u0437\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044c landscape \u0444\u043e\u0442\u043e ', upload_to='new_image', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430')),
                ('draft', models.BooleanField(default=False)),
                ('publish', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
                'verbose_name': '\u043d\u043e\u0432\u043e\u0441\u0442\u043d\u0430\u044f \u0441\u0442\u0430\u0442\u044c\u044f',
                'verbose_name_plural': '\u043d\u043e\u0432\u043e\u0441\u0442\u043d\u044b\u0435 \u0441\u0442\u0430\u0442\u044c\u0438',
            },
        ),
    ]
