# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-07-29 11:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique_for_date='posted', verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('description', models.TextField(verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u0441\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u0435')),
                ('content', models.TextField(verbose_name='\u041f\u043e\u043b\u043d\u043e\u0435 \u0441\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u0435')),
                ('posted', models.DateTimeField(db_index=True, default=datetime.datetime(2017, 7, 29, 14, 19, 28, 118327), verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d\u0430')),
            ],
            options={
                'ordering': ['-posted'],
                'verbose_name': '\u043d\u043e\u0432\u043e\u0441\u0442\u043d\u0430\u044f \u0441\u0442\u0430\u0442\u044c\u044f',
                'verbose_name_plural': '\u043d\u043e\u0432\u043e\u0441\u0442\u043d\u044b\u0435 \u0441\u0442\u0430\u0442\u044c\u0438',
            },
        ),
    ]
