# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-05-25 15:01
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180525_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='\u0411\u0443\u0434\u0435\u0442 \u043b\u0443\u0447\u0448\u0435 \u0437\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044c landscape \u0444\u043e\u0442\u043e ', null=True, upload_to='new_image', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430'),
        ),
    ]
