# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-05-25 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180525_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='publish',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
