# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-08-03 10:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20170802_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(help_text='\u041f\u043e\u0436\u0430\u043b\u0443\u0439\u0441\u0442\u0430 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0439\u0442\u0435 \u0433\u043e\u0440\u0438\u0437\u043e\u043d\u0442\u0430\u043b\u044c\u043d\u043e\u0435 \u0444\u043e\u0442\u043e', upload_to='new_image', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2017, 8, 3, 13, 3, 58, 301389), verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d\u0430'),
        ),
    ]
