# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-08-04 09:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20170803_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(help_text='\u0411\u0443\u0434\u0435\u0442 \u043b\u0443\u0447\u0448\u0435 \u0437\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044c landscape \u0444\u043e\u0442\u043e ', upload_to='new_image', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2017, 8, 4, 12, 40, 50, 796182), verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d\u0430'),
        ),
    ]
