# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-07-18 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='\u0423\u0421\u041b\u0423\u0413\u0410')),
                ('text', models.CharField(blank=True, default=None, max_length=2000, null=True, unique=True, verbose_name='\u0422\u0415\u041a\u0421\u0422 \u0414\u041b\u042f \u0421\u0422\u0420\u0410\u041d\u0418\u0426\u042b')),
                ('link', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='\u0421\u0421\u042b\u041b\u041a\u0410 \u041d\u0410 \u041e\u0422\u041f\u0420\u0410\u0412\u041a\u0423 \u0417\u0410\u042f\u0412\u041a\u0418')),
            ],
        ),
    ]
