# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-07-28 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import precise_bbcode.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='\u0423\u0421\u041b\u0423\u0413\u0410')),
                ('_text_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('text', precise_bbcode.fields.BBCodeTextField(blank=True, default=None, no_rendered_field=True, null=True, verbose_name='\u0422\u0415\u041a\u0421\u0422 \u0414\u041b\u042f \u0421\u0422\u0420\u0410\u041d\u0418\u0426\u042b \u0423\u0421\u041b\u0423\u0413\u0418')),
                ('link', models.CharField(blank=True, choices=[('/call_order/', '\u0417\u0410\u041a\u0410\u0417\u0410\u0422\u042c \u0417\u0412\u041e\u041d\u041e\u041a'), ('/order/maintenance/dgu/', '\u0417\u0410\u041a\u0410\u0417\u0410\u0422\u042c \u0422\u0415\u0425\u041e\u0411\u0421\u041b\u0423\u0416\u0418\u0412\u0410\u041d\u0418\u0415 \u0414\u0413\u0423'), ('/order/maintenance/ups/', '\u0417\u0410\u041a\u0410\u0417\u0410\u0422\u042c \u0422\u0415\u0425\u041e\u0411\u0421\u041b\u0423\u0416\u0418\u0412\u0410\u041d\u0418\u0415 \u0418\u0411\u041f'), ('/order/repair/dgu/', '\u0417\u0410\u041a\u0410\u0417\u0410\u0422\u042c \u0420\u0415\u041c\u041e\u041d\u0422 \u0414\u0413\u0423'), ('/order/repair/ups/', '\u0417\u0410\u041a\u0410\u0417\u0410\u0422\u042c \u0420\u0415\u041c\u041e\u041d\u0422 \u0418\u0411\u041f')], max_length=30, verbose_name='\u0415\u0421\u041b\u0418 \u041d\u0423\u0416\u041d\u041e, \u0412\u042b\u0411\u0415\u0420\u0418\u0422\u0415 \u041a\u041d\u041e\u041f\u041a\u0423 \u041d\u0410 \u0417\u0410\u041a\u0410\u0417 \u0423\u0421\u041b\u0423\u0413\u0418')),
            ],
        ),
    ]
