# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-07-28 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='serv_name',
        ),
    ]
