# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-08-01 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20170728_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='_text_rendered',
            new_name='_content_rendered',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='text',
            new_name='content',
        ),
    ]
