# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-07-20 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import precise_bbcode.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20170719_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='_text_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='link',
            field=models.CharField(blank=True, default='/send-email/', max_length=30, verbose_name='\u0421\u0421\u042b\u041b\u041a\u0410 \u041d\u0410 \u041e\u0422\u041f\u0420\u0410\u0412\u041a\u0423 \u0417\u0410\u042f\u0412\u041a\u0418 \u041d\u0410 \u0423\u0421\u041b\u0423\u0413\u0423'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='\u0423\u0421\u041b\u0423\u0413\u0410'),
        ),
        migrations.AlterField(
            model_name='service',
            name='text',
            field=precise_bbcode.fields.BBCodeTextField(blank=True, default=None, max_length=2000, no_rendered_field=True, null=True, unique=True, verbose_name='\u0422\u0415\u041a\u0421\u0422 \u0414\u041b\u042f \u0421\u0422\u0420\u0410\u041d\u0418\u0426\u042b \u0423\u0421\u041b\u0423\u0413\u0418'),
        ),
    ]
