# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-07-20 09:16
from __future__ import unicode_literals

from django.db import migrations
import precise_bbcode.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20170720_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='text',
            field=precise_bbcode.fields.BBCodeTextField(blank=True, default=None, max_length=2000, no_rendered_field=True, null=True, verbose_name='\u0422\u0415\u041a\u0421\u0422 \u0414\u041b\u042f \u0421\u0422\u0420\u0410\u041d\u0418\u0426\u042b \u0423\u0421\u041b\u0423\u0413\u0418'),
        ),
    ]
