# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-07-26 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20170721_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='link',
            field=models.CharField(blank=True, choices=[('/call_order/', '\u0417\u0410\u041a\u0410\u0417\u0410\u0422\u042c \u0417\u0412\u041e\u041d\u041e\u041a'), ('/maintenance_order/', '\u0417\u0410\u042f\u0412\u041a\u0410 \u041d\u0410 \u0422\u0415\u0425\u041e\u0411\u0421\u041b\u0423\u0416\u0418\u0412\u0410\u041d\u0418\u0415'), ('/repair_order/', '\u0417\u0410\u042f\u0412\u041a\u0410 \u041d\u0410 \u0420\u0415\u041c\u041e\u041d\u0422')], max_length=30, verbose_name='\u0415\u0421\u041b\u0418 \u041d\u0423\u0416\u041d\u041e, \u0412\u042b\u0411\u0415\u0420\u0418\u0422\u0415 \u041a\u041d\u041e\u041f\u041a\u0423 \u041d\u0410 \u0417\u0410\u041a\u0410\u0417 \u0423\u0421\u041b\u0423\u0413\u0418'),
        ),
    ]
