# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-07-02 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=10, unique=True, verbose_name='\u041c\u0430\u0440\u043a\u0430  \u0434\u0438\u0437\u0435\u043b\u044c\u0433\u0435\u043d\u0435\u0440\u0430\u0442\u043e\u0440\u0430')),
                ('stand_by_kva', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='ESP(Stand-by)/\u043a\u0412\u0410')),
                ('stand_by_kw', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='ESP(Stand-by)/\u043a\u0412\u0442')),
                ('prime_kva', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='PRP(Prime)/\u043a\u0412\u0410')),
                ('prime_kw', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='PRP(Prime)/\u043a\u0412\u0442')),
                ('engine_model', models.SlugField(max_length=10, verbose_name='\u041c\u043e\u0434\u0435\u043b\u044c \u0434\u0432\u0438\u0433\u0430\u0442\u0435\u043b\u044f')),
                ('spec', models.FileField(upload_to=b'', verbose_name='pdf \u0444\u0430\u0439\u043b \u0441\u043f\u0435\u0446\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u0438')),
            ],
        ),
        migrations.CreateModel(
            name='Gensetengine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(max_length=20, unique=True, verbose_name='\u043f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c \u0434\u0432\u0438\u0433\u0430\u0442\u0435\u043b\u044f \u0414\u0413\u0423')),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to='catalog/dgu/logo', verbose_name='\u041b\u043e\u0433\u043e\u0442\u0438\u043f \u043c\u0430\u0440\u043a\u0438 \u0434\u0432\u0438\u0433\u0430\u0442\u0435\u043b\u044f \u0414\u0413\u0423')),
                ('text', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442, \u043a\u043e\u0442. \u0431\u0443\u0434\u0435\u0442 \u0432\u044b\u0432\u043e\u0434\u0438\u0442\u044c\u0441\u044f \u043f\u0435\u0440\u0435\u0434 \u0442\u0430\u0431\u043b\u0438\u0446\u0435\u0439 \u0441 \u043c\u043e\u0434\u0435\u043b\u044f\u043c\u0438 \u0434\u0438\u0437\u0435\u043b\u044c\u0433\u0435\u043d\u0435\u0440\u0430\u0442\u043e\u0440\u043e\u0432')),
            ],
        ),
        migrations.AddField(
            model_name='genset',
            name='gensetengine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Gensetengine', verbose_name='\u041c\u0430\u0440\u043a\u0430 \u0434\u0432\u0438\u0433\u0430\u0442\u0435\u043b\u044f'),
        ),
    ]
