# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-07-02 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gensetengine',
            name='text',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442, \u043a\u043e\u0442. \u0431\u0443\u0434\u0435\u0442 \u0432\u044b\u0432\u043e\u0434\u0438\u0442\u044c\u0441\u044f \u043f\u0435\u0440\u0435\u0434 \u0442\u0430\u0431\u043b\u0438\u0446\u0435\u0439 \u0441 \u043c\u043e\u0434\u0435\u043b\u044f\u043c\u0438 \u0434\u0438\u0437\u0435\u043b\u044c\u0433\u0435\u043d\u0435\u0440\u0430\u0442\u043e\u0440\u043e\u0432'),
        ),
    ]
