# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-07-08 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170703_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genset',
            name='engine_model',
            field=models.SlugField(max_length=20, unique=True, verbose_name='\u041c\u043e\u0434\u0435\u043b\u044c \u0434\u0432\u0438\u0433\u0430\u0442\u0435\u043b\u044f'),
        ),
        migrations.AlterField(
            model_name='genset',
            name='spec',
            field=models.FileField(blank=True, default=None, null=True, upload_to='catalog/dgu/spec_pdf', verbose_name='pdf \u0444\u0430\u0439\u043b \u0441\u043f\u0435\u0446\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='gensetengine',
            name='engine',
            field=models.CharField(max_length=20, unique=True, verbose_name='\u041f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c \u0434\u0432\u0438\u0433\u0430\u0442\u0435\u043b\u044f \u0414\u0413\u0423'),
        ),
        migrations.AlterField(
            model_name='gensetengine',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='catalog/dgu/logo', verbose_name='\u041b\u043e\u0433\u043e\u0442\u0438\u043f'),
        ),
        migrations.AlterField(
            model_name='gensetengine',
            name='text',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442, \u043a\u043e\u0442. \u0431\u0443\u0434\u0435\u0442 \u0432\u044b\u0432\u043e\u0434\u0438\u0442\u044c\u0441\u044f \u043f\u0435\u0440\u0435\u0434 ...'),
        ),
    ]
