# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-07-12 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20170712_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genset',
            name='engine_model',
            field=models.CharField(max_length=20, verbose_name='\u041c\u043e\u0434\u0435\u043b\u044c \u0434\u0432\u0438\u0433\u0430\u0442\u0435\u043b\u044f'),
        ),
    ]
