# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-05-26 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.ImageField(upload_to='certificates', verbose_name='\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0444\u0430\u0439\u043b \u0432 \u0444\u043e\u0440\u043c\u0430\u0442\u0435 .jpg \u0438\u043b\u0438 .jpeg')),
                ('certificate_1x', models.ImageField(default=None, null=True, upload_to='certificate')),
                ('certificate_2x', models.ImageField(default=None, null=True, upload_to='certificate')),
            ],
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='marka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Marka', verbose_name='\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0438\u0437 \u0441\u043f\u0438\u0441\u043a\u0430 \u0438\u043b\u0438 \u0432\u0432\u0435\u0434\u0438\u0442\u0435 \u043d\u043e\u0432\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043c\u0430\u0440\u043a\u0438:'),
        ),
    ]
