# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-05-28 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otziv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otziv', models.ImageField(upload_to='otziv', verbose_name='\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0444\u0430\u0439\u043b \u043e\u0442\u0437\u044b\u0432\u0430 \u0432 \u0444\u043e\u0440\u043c\u0430\u0442\u0435 .jpg \u0438\u043b\u0438 .jpeg')),
                ('otziv_1x', models.ImageField(default=None, null=True, upload_to='otziv')),
                ('otziv_2x', models.ImageField(default=None, null=True, upload_to='otziv')),
                ('text', models.TextField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_1x',
            field=models.ImageField(default=None, null=True, upload_to='certificates'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_2x',
            field=models.ImageField(default=None, null=True, upload_to='certificates'),
        ),
    ]
