# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-05-31 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20170528_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otziv',
            name='text',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
