# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-06-06 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20170531_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callorderuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u0418\u041c\u042f')),
                ('text', models.CharField(max_length=200, verbose_name='\u0412\u041e\u041f\u0420\u041e\u0421')),
                ('published_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='marka',
        ),
    ]
